---
addons: ~
apt: ~
before_install:
   - "mysql -e 'CREATE DATABASE IF NOT EXISTS employe_bugs;'"
install: true
jdk:
   - openjdk14
language: java
packages:
   - oracle-java8-installer
script:
   - "mvn install"
services:
   - mysql
