language: java

jdk:
- oraclejdk9

sudo: false
script: mvn clean verify

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS employe_bugs;'

services:
- mysql

notifications:
   email:dani.modoc@yahoo.com

