language: java

jdk:
- openjdk14

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS employe_bugs;'
install: true
script:
   - mvn install
services:
- mysql

notifications:
   email:dani.modoc@yahoo.com

