language: java

jdk:
- oraclejdk9

install: true
script: ./mvn clean install

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS employe_bugs;'

services:
- mysql

notifications:
   email:dani.modoc@yahoo.com

